/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lat2;

/**
 *
 * @author SMK TELKOM
 */
public class Aritmatika extends javax.swing.JFrame {
    String jns ="";
    int jml;
   
    public Aritmatika() {
        initComponents();
        getJumlah();
        setJenis();
        panel.setVisible(false);
        pilihanbil.setEnabled(false);
        bil1.setVisible(false);
        bil2.setVisible(false);
        bil3.setVisible(false);
        bil4.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        b4.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jenis = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        ket = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pilihanbil = new javax.swing.JComboBox<>();
        bil1 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JLabel();
        b2 = new javax.swing.JTextField();
        bil3 = new javax.swing.JLabel();
        b3 = new javax.swing.JTextField();
        bil4 = new javax.swing.JLabel();
        b4 = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 199, 31);

        jenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Penjumlahan", "Pengurangan", "Perkalian", "Pembagian" }));
        jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisActionPerformed(evt);
            }
        });
        getContentPane().add(jenis);
        jenis.setBounds(260, 50, 120, 40);

        jPanel1.setBackground(new java.awt.Color(0, 255, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Jenis Aritmatika");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 60, 100, 20);

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Operasi"));
        panel.setForeground(new java.awt.Color(204, 204, 204));
        panel.setLayout(null);
        panel.add(ket);
        ket.setBounds(115, 16, 130, 30);

        jLabel4.setText("Jumlah Bilangan");
        panel.add(jLabel4);
        jLabel4.setBounds(20, 60, 90, 30);

        pilihanbil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "2", "3", "4" }));
        pilihanbil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanbilActionPerformed(evt);
            }
        });
        panel.add(pilihanbil);
        pilihanbil.setBounds(130, 60, 200, 30);

        bil1.setText("Bilangan 1");
        panel.add(bil1);
        bil1.setBounds(30, 110, 80, 20);
        panel.add(b1);
        b1.setBounds(130, 110, 200, 30);

        bil2.setText("Bilangan 2");
        panel.add(bil2);
        bil2.setBounds(30, 150, 80, 20);
        panel.add(b2);
        b2.setBounds(130, 150, 200, 30);

        bil3.setText("Bilangan 3");
        panel.add(bil3);
        bil3.setBounds(30, 190, 80, 20);
        panel.add(b3);
        b3.setBounds(130, 190, 200, 30);

        bil4.setText("Bilangan 4");
        panel.add(bil4);
        bil4.setBounds(30, 230, 80, 20);
        panel.add(b4);
        b4.setBounds(130, 230, 200, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        panel.add(hitung);
        hitung.setBounds(160, 270, 160, 30);
        panel.add(hasil);
        hasil.setBounds(70, 310, 270, 90);

        jPanel1.add(panel);
        panel.setBounds(30, 110, 390, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 540);

        setBounds(0, 0, 482, 584);
    }// </editor-fold>//GEN-END:initComponents

    private void jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisActionPerformed
        // TODO add your handling code here:
        setJenis();
    }//GEN-LAST:event_jenisActionPerformed
public void setJenis(){
        if(jenis.getSelectedItem().equals("Penjumlahan")){
            jns="Penjumlahan";
            ket.setText("Penjumlahan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Pengurangan")){
            jns="Pengurangan";
            ket.setText("Pengurangan");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Perkalian")){
            jns="Perkalian";
            ket.setText("Perkalian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        else if (jenis.getSelectedItem().equals("Pembagian")){
            jns="Pembagian";
            ket.setText("Pembagian");
            panel.setVisible(true);
            pilihanbil.setEnabled(true);
        }
        
    }
    private void pilihanbilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanbilActionPerformed
        // TODO add your handling code here:
        getJumlah();
    }//GEN-LAST:event_pilihanbilActionPerformed
 public void getJumlah(){
        if(pilihanbil.getSelectedItem().equals("2")){
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(false);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(false);
            bil4.setVisible(false);
            jml = 2;
        }else if(pilihanbil.getSelectedItem().equals("3")){
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(false);
            bil1.setVisible(true);
            bil2.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(false);
            jml = 3;
        }else if(pilihanbil.getSelectedItem().equals("4")){
            b1.setVisible(true);
            b2.setVisible(true);
            b3.setVisible(true);
            b4.setVisible(true);
            bil3.setVisible(true);
            bil4.setVisible(true);
            bil1.setVisible(true);
            bil2.setVisible(true);
            jml = 4;
        }
        
    }
    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        double hsl = 0.0;
        double a1, a2, a3, a4;
        a1 = Double.parseDouble(b1.getText().toString());
        a2 = Double.parseDouble(b2.getText().toString());
        a3 = Double.parseDouble(b3.getText().toString());
        a4 = Double.parseDouble(b4.getText().toString());
        
        if(jns.equals("Penjumlahan")){
            if(jml == 2){
                hsl = a1+a2;
                hasil.setText(""+a1+ " + "+a2+ " = " +hsl);
            }
            else if(jml == 3){
                hsl = a1+a2+a3;
                hasil.setText(""+a1+ " + "+a2+ " + "+a3+ " = " +hsl);
            }
             else if(jml == 4){
                hsl = a1+a2+a3+a4;
                hasil.setText(""+a1+ " + "+a2+ " + "+a3+ " + "+a4+ " = " +hsl);
            }
            
        }
        else if(jns.equals("Pengurangan")){
            if(jml == 2){
                hsl = a1-a2;
                hasil.setText(""+a1+ " - "+a2+ " = " +hsl);
            }
            else if(jml == 3){
                hsl = a1-a2-a3;
                hasil.setText(""+a1+ " - "+a2+ " - "+a3+ " = " +hsl);
            }
             else if(jml == 4){
                hsl = a1-a2-a3-a4;
                hasil.setText(""+a1+ " - "+a2+ " - "+a3+ " - "+a4+ " = " +hsl);
            }
        }
        else if(jns.equals("Perkalian")){
            if(jml == 2){
                hsl = a1*a2;
                hasil.setText(""+a1+ " x "+a2+ " = " +hsl);
            }
            else if(jml == 3){
                hsl = a1*a2*a3;
                hasil.setText(""+a1+ " x "+a2+ " x "+a3+ " = " +hsl);
            }
             else if(jml == 4){
                hsl = a1*a2*a3*a4;
                hasil.setText(""+a1+ " x "+a2+ " x "+a3+ " x "+a4+ " = " +hsl);
            }
        }
        else if(jns.equals("Pembagian")){
            if(jml == 2){
                hsl = a1/a2;
                hasil.setText(""+a1+ " : "+a2+ " = " +hsl);
            }
            else if(jml == 3){
                hsl = a1/a2/a3;
                hasil.setText(""+a1+ " : "+a2+ " : "+a3+ " = " +hsl);
            }
             else if(jml == 4){
                hsl = a1/a2/a3/a4;
                hasil.setText(""+a1+ " : "+a2+ " : "+a3+ " : "+a4+ " = " +hsl);
            }
        }
    }//GEN-LAST:event_hitungActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField b4;
    private javax.swing.JLabel bil1;
    private javax.swing.JLabel bil2;
    private javax.swing.JLabel bil3;
    private javax.swing.JLabel bil4;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jenis;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<String> pilihanbil;
    // End of variables declaration//GEN-END:variables
}
